### ISSUE TITLE
Shop.org - Preparation

### ISSUE THREAD

**Issue by yuval-skava** [yuval-skava/marketing#6]
Positioning - TBD
Target audience (who will attend and who do we care about?)

Booth design
Demos
General collaterals
AR/PR debrief/marketing template
Case studies

**Comment by JocelynSkava** [comment]
- [ ] Positioning
- [x] target audience: in briefing package: https://skava.app.box.com/files/0/f/8954511090/1/f_73543228781
- [ ] Who do we care about? @yuval-skava can we discuss this?
- [x] Booth design: https://skava.app.box.com/files/0/f/8917978590/1/f_92803953082
- [ ] Demos TBD
- [ ] General collaterals
- [ ] AR meeting: Will arrange with Infosys
- PR, no efforts have been made for launch a PR campaign
- Case studies: Case studies are something we've been wanting to do. Phil was talking to FTD about doing a case study for them. He was offering a discount on our platform in exchange for a case study.
